DELETE http://localhost:3001/api/persons/697b109c65b632a3b8d9fa1f

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Monkey D Dragon", 
    "number": "119128"
}

###
GET http://localhost:3001/api/persons
###
PUT http://localhost:3001/api/persons/697828bf856e27e2746027a2
Content-Type: application/json

{
    "name": "Pranay2", 
    "number": "12"
}